### ISSUE TITLE
Problem with new HA core version core-2021.6.2

### ISSUE THREAD

**Issue by alejandrorg-hub** [mac-zhou/midea-ac-py#67] opened 2021-06-08 01:17 UTC
When update to a noew core versiion 6.2, apear a new error at the  configuration.yaml, and can't validate.
The error report is that not recognize platform midea_ac

Please, do you know how resolve this problem?

**Comment by captennemo** [comment] 2021-06-08 11:17
Have you checked the HA logfile? It probably say something like "The custom integration 'midea_ac' does not have a valid version key (None) in the manifest file". If so add` , "version: "1.0.0"` to the midea_ac manifest file and restart HA.

**Comment by yhwl8888** [comment] 2021-06-08 12:37
"version: "1.0.0"  restart HA. The problem is still adding the version number. Can you package and upload your media AC

**Comment by yhwl8888** [comment] 2021-06-08 12:38
> Have you checked the HA logfile? It probably say something like "The custom integration 'midea_ac' does not have a valid version key (None) in the manifest file". If so add to the midea_ac manifest file and restart HA.` , "version: "1.0.0"`

"version: "1.0.0" restart HA. The problem is still adding the version number. Can you package and upload your media AC

**Comment by mattlward** [comment] 2021-06-08 19:58
I am having the same issue with my install, I added the version info as well.

**Comment by mattlward** [comment] 2021-06-09 04:29
The update you just pushed fixed my issue.  Thanks!

**Comment by mac-zhou** [comment] 2021-06-09 04:48
#58

**Closed by mac-zhou** 2021-06-09 04:48 UTC
Labels: bug
